Update actions file

diff --git a/.github/workflows/.github-actions.yml b/.github/workflows/.github-actions.yml
--- a/.github/workflows/.github-actions.yml
+++ b/.github/workflows/.github-actions.yml
@@ -1,4 +1,4 @@
-name: Deployment
+name: CI
 
 on:
   push:
@@ -27,7 +27,7 @@ jobs:
           php -v
           composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
 
-      - name: 'Compress composer folder'
+      - name: Compress composer folder
         run: tar -czvf composer.tgz vendor/
 
       - name: Upload composer assets
@@ -40,14 +40,6 @@ jobs:
   phpunit:
     runs-on: ubuntu-latest
     needs: [composer]
-    #    services:
-    #      mariadb:
-    #        image: mariadb:10.3
-    #        env:
-    #          MYSQL_ROOT_PASSWORD: root
-    #        ports:
-    #          - 3306:3306
-    #        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
     steps:
       - name: Checkout the repository
@@ -60,7 +52,7 @@ jobs:
         with:
           name: composer
 
-      - name: Unpack artifacts
+      - name: Unpack composer artifacts
         run: |
           tar xvfz composer.tgz
 
@@ -71,16 +63,17 @@ jobs:
           extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
           coverage: xdebug
 
-      #      - name: Create temp database
-      #        run: |
-      #          mysql --host 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS laravel_db"
-
       - name: Execute tests
         run: |
           cp .env.testing .env
           php -v
           ./vendor/phpunit/phpunit/phpunit --version
-          phpdbg -qrr ./vendor/phpunit/phpunit/phpunit -v --colors=never --stderr --coverage-clover=coverage.xml
+          ./vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.xml
+          export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
+          bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
+
+      - name: Upload code coverage
+        run: |
           export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
           bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
 
@@ -91,7 +84,7 @@ jobs:
           path: ~/storage/logs
           retention-days: 3
 
-  fabpot-security-checker:
+  package-security-checker:
     runs-on: ubuntu-latest
     needs: [composer]
 
